In [1]:
import gym_wordle
from stable_baselines3 import DQN, PPO, common
import numpy as np
from tqdm import tqdm

In [2]:
env = gym_wordle.wordle.WordleEnv()
env = common.monitor.Monitor(env)

print(env)

<Monitor<WordleEnv instance>>


In [3]:
total_timesteps = 20_000
model = PPO("MlpPolicy", env, verbose=1, device='cuda')
model.learn(total_timesteps=total_timesteps)

Using cuda device
Wrapping the env in a DummyVecEnv.
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 6        |
|    ep_rew_mean     | 2.14     |
| time/              |          |
|    fps             | 750      |
|    iterations      | 1        |
|    time_elapsed    | 2        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6           |
|    ep_rew_mean          | 4.59        |
| time/                   |             |
|    fps                  | 625         |
|    iterations           | 2           |
|    time_elapsed         | 6           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.022059526 |
|    clip_fraction        | 0.331       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.47       |
|    explained_vari

In [4]:
model.save("dqn_wordle")

In [5]:
model = PPO.load("dqn_wordle")

In [7]:
env = gym_wordle.wordle.WordleEnv()

for i in tqdm(range(1000)):
        
    state, info = env.reset()

    done = False

    wins = 0

    while not done:

        action, _states = model.predict(state, deterministic=True)

        state, reward, done, truncated, info = env.step(action)

    if info["correct"]:
        wins += 1

print(state, reward, info)

print(wins)


100%|██████████| 1000/1000 [00:03<00:00, 252.17it/s]

[[ 7 18  1 19 16  3  3  3  2  3]
 [16  9  5 14  4  3  3  3  3  3]
 [16  9  5 14  4  3  3  3  3  3]
 [16  9  5 14  4  3  3  3  3  3]
 [ 7 18  1 19 16  3  3  3  2  3]
 [ 7 18  1 19 16  3  3  3  2  3]] -54 {'correct': False, 'guesses': defaultdict(<class 'int'>, {'grasp': 3, 'piend': 3})}
0
