In [2]:
import gym
import gym_wordle
from stable_baselines3 import DQN
import numpy as np

In [3]:
env = gym.make("Wordle-v0")
done = False

print(env)

<WordleEnv<Wordle-v0>>


In [4]:
model = DQN("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=10000)

Using cuda device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


/usr/local/lib/python3.8/dist-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | -6       |
|    exploration_rate | 0.977    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 8958     |
|    time_elapsed     | 0        |
|    total_timesteps  | 24       |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | -6       |
|    exploration_rate | 0.954    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 8537     |
|    time_elapsed     | 0        |
|    total_timesteps  | 48       |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 6        |
|    ep_rew_mean      | -6       |
|    exploration_rate | 0.932    |
| time/               |          |
|    episodes       

In [15]:
def test(model):

    end_rewards = []

    for i in range(1000):
        
        state = env.reset()

        done = False

        while not done:

            action, _states = model.predict(state, deterministic=True)

            state, reward, done, info = env.step(action)

        end_rewards.append(reward == 0)
        if (reward == 0):
            print(state)

    return np.sum(end_rewards) / len(end_rewards)

In [17]:
print(test(model))
model.save("dqn_wordle")

[[1 3 3 3 1 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 3 3 3 1 0 0 0 0 0]
 [1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
0.002
