In [1]:
import gym
import gym_wordle
from stable_baselines3 import DQN, PPO, common
import numpy as np
import tqdm

In [2]:
env = gym_wordle.wordle.WordleEnv()
env = common.monitor.Monitor(env)

print(env)

<Monitor<WordleEnv instance>>


In [3]:
total_timesteps = 20_000
model = PPO("MlpPolicy", env, verbose=1, device='cuda')
model.learn(total_timesteps=total_timesteps)

Using cpu device
Wrapping the env in a DummyVecEnv.
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 6        |
|    ep_rew_mean     | 5.59     |
| time/              |          |
|    fps             | 544      |
|    iterations      | 1        |
|    time_elapsed    | 3        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 6           |
|    ep_rew_mean          | 1.77        |
| time/                   |             |
|    fps                  | 245         |
|    iterations           | 2           |
|    time_elapsed         | 16          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.021515464 |
|    clip_fraction        | 0.335       |
|    clip_range           | 0.2         |
|    entropy_loss         | -9.47       |
|    explained_varia

In [4]:
model.save("dqn_wordle")

In [5]:
model = PPO.load("dqn_wordle")

c:\Repository\cse151b-final-project\env\Lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object clip_range. Consider using `custom_objects` argument to replace this object.
Exception: code() argument 13 must be str, not int
  warnings.warn(
c:\Repository\cse151b-final-project\env\Lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object lr_schedule. Consider using `custom_objects` argument to replace this object.
Exception: code() argument 13 must be str, not int
  warnings.warn(


In [6]:
env = gym_wordle.wordle.WordleEnv()

for i in range(10):
        
    state, info = env.reset()

    done = False

    wins = 0

    while not done:

        action, _states = model.predict(state, deterministic=True)

        state, reward, done, truncated, info = env.step(action)

    if info["correct"]:
        wins += 1

print(wins)


[[16  1  9 19  5  3  2  3  3  1]
 [18  8  5 13  5  2  3  2  3  1]
 [16  1  9 19  5  3  2  3  3  1]
 [16  1  9 19  5  3  2  3  3  1]
 [16  1  9 19  5  3  2  3  3  1]
 [16  1  9 19  5  3  2  3  3  1]]
[[16  1  9 19  5  3  3  3  3  3]
 [18  8  5 13  5  3  2  3  3  3]
 [16  1  9 19  5  3  3  3  3  3]
 [16  1  9 19  5  3  3  3  3  3]
 [16  1  9 19  5  3  3  3  3  3]
 [16  1  9 19  5  3  3  3  3  3]]
[[16  1  9 19  5  3  3  1  3  3]
 [18  8  5 13  5  3  3  3  3  3]
 [16  1  9 19  5  3  3  1  3  3]
 [16  1  9 19  5  3  3  1  3  3]
 [16  1  9 19  5  3  3  1  3  3]
 [16  1  9 19  5  3  3  1  3  3]]
[[16  1  9 19  5  1  2  2  3  3]
 [18  8  5 13  5  3  3  3  3  3]
 [16  1  9 19  5  1  2  2  3  3]
 [16  1  9 19  5  1  2  2  3  3]
 [16  1  9 19  5  1  2  2  3  3]
 [16  1  9 19  5  1  2  2  3  3]]
[[16  1  9 19  5  1  1  3  1  1]
 [18  1 11  5  4  2  1  3  2  3]
 [16  1  9 19  5  1  1  3  1  1]
 [16  1  9 19  5  1  1  3  1  1]
 [16  1  9 19  5  1  1  3  1  1]
 [16  1  9 19  5  1  1  3  1  1]]
[[16 

In [ ]:
print()