In [83]:
import gym
import gym_wordle
from stable_baselines3 import DQN, PPO, common
import numpy as np
import tqdm

In [84]:
env = gym_wordle.wordle.WordleEnv()
env = common.monitor.Monitor(env)

print(env)

<Monitor<WordleEnv instance>>


In [85]:
total_timesteps = 1000
model = PPO("MlpPolicy", env, verbose=1)
model.learn(total_timesteps=total_timesteps)

Using cuda device
Wrapping the env in a DummyVecEnv.


In [ ]:
model.save("dqn_wordle")

In [ ]:
model = PPO.load("dqn_wordle")

In [ ]:
env = gym_wordle.wordle.WordleEnv()

for i in range(1):
        
    state = env.reset()

    done = False

    wins = 0

    while not done:

        action, _states = model.predict(state, deterministic=True)

        state, reward, done, info = env.step(action)

        print(state, reward, done, info)

    if info["correct"]:
        wins += 1
        
    #end_rewards.append(reward == 0)
    
#return np.sum(end_rewards) / len(end_rewards)


[[16 18  5 15 14  3  3  1  3  3]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]] -1.0 False {}
[[16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]] -1.0 False {}
[[16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]] -1.0 False {}
[[16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]] -1.0 False {}
[[16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14  3  3  1  3  3]
 [16 18  5 15 14

KeyError: 'correct'